### ISSUE TITLE
将本应用上传至 homebrew

### ISSUE THREAD

**Issue by PhotonQuantum** [lihaoyun6/AppDimmer#1]
不知本项目有无支持 homebrew 包管理的计划？应该可以上传到 homebrew cask，这样安装起来会更方便

**Comment by lihaoyun6** [comment]
> 不知本项目有无支持 homebrew 包管理的计划？应该可以上传到 homebrew cask，这样安装起来会更方便

现在可以使用:
```bash
brew install lihaoyun6/tap/appdimmer --cask
```
来安装AppDimmer了
