### ISSUE TITLE
浏览器全屏观看视频时 有时不生效

### ISSUE THREAD

**Issue by xianyongjian080402** [lihaoyun6/AppDimmer#11]
浏览器全屏观看视频时 有时不生效 有时生效

**Comment by xianyongjian080402** [comment]
这个我目前采用的是手动解决（点两下
![截屏2022-08-09 12 25 47](https://user-images.githubusercontent.com/70191815/183563976-ae6b1614-cbce-4e20-b85f-666cca972327.png)
但是我更希望修复这个问题

**Comment by xianyongjian080402** [comment]
好的 感谢

**Comment by lihaoyun6** [comment]
> 好的 感谢

v0.4.1已发布, 已经修复了上述问题. 请更新即可

**Comment by xianyongjian080402** [comment]
好家伙 这么快
