### ISSUE TITLE
窗口较窄时打开表情功能会超出遮罩的范围

### ISSUE THREAD

**Issue by juzijun233** [lihaoyun6/AppDimmer#2]
如题
![image](https://user-images.githubusercontent.com/43207394/144617807-ac360c24-ab49-4088-90b1-ca91df70ae53.png)

**Comment by lihaoyun6** [comment]
这种浮动窗体的动态检测与归类是一个难点. 投入的精力与产出的效果不成正比.
我暂时不太想搞这种(包括: 表情选择器, 个人资料窗口等)

**Comment by juzijun233** [comment]
不知大佬是否有意另做一个全局遮罩的软件，因为有些软件、窗口以及流媒体播放并不适配深色模式，IOS上还可以使用降低白点值来达到效果

**Comment by lihaoyun6** [comment]
> 不知大佬是否有意另做一个全局遮罩的软件，因为有些软件、窗口以及流媒体播放并不适配深色模式，IOS上还可以使用降低白点值来达到效果

DimQQ已经正式重命名为AppDimmer. 转为了一款通用型的App遮罩软件. 可以添加任何你想要调整亮度的App到AppDimmer的调光名单.  
你提到的这个需求我已经解决了, 请下载使用最新版的AppDimmer即可
