### ISSUE TITLE
你好，很棒的软件，已打赏。有个问题，请问为啥有的程序无法识别

### ISSUE THREAD

**Issue by asdqian** [lihaoyun6/AppDimmer#5]
识别不到应用名字，显示  “：未启用”，点击也没反应。  这个程序叫flomo。跟其他软件不一样的是，我从他的网站下载ZIP解压后，没有安装的步骤，也没有.dmg的后缀，是在文件夹里直接打开的。因为没有安装，所以启动台里也没有，还是我把文件复制到应用程序文件夹，才在启动台里显示。不过APP DIMMER显示  “：未启用”。所以没法应用夜间模式。 方便的话，麻烦帮忙看看是怎么一回事，多谢。

**Comment by lihaoyun6** [comment]
> 识别不到应用名字，显示 “：未启用”，点击也没反应。 这个程序叫flomo。跟其他软件不一样的是，我从他的网站下载ZIP解压后，没有安装的步骤，也没有.dmg的后缀，是在文件夹里直接打开的。因为没有安装，所以启动台里也没有，还是我把文件复制到应用程序文件夹，才在启动台里显示。不过APP DIMMER显示 “：未启用”。所以没法应用夜间模式。 方便的话，麻烦帮忙看看是怎么一回事，多谢。

感谢您的支持, 此问题已在 v0.3.8 版本中予以修复. 可[点此](https://github.com/lihaoyun6/AppDimmer/releases/tag/0.3.8)前往下载更新.  
如果您是使用 Homebrew 安装的 AppDimmer, 请使用命令行进行更新:
```bash
brew upgrade appdimmer
```

另外建议您在为 flomo 启用 AppDimmer 后, 同时为其关闭"窗口筛选器".  
如果您不为 flomo 关闭此选项, 则 flomo 的菜单栏弹出窗口无法被识别并遮盖.
<img width="231" alt="Xnip2022-05-22_21-00-19" src="https://user-images.githubusercontent.com/16348097/169696443-0a50a21f-631f-490e-a56d-7f54b3657879.png">

**如果您还有其他任何问题, 欢迎回复. 如没有, 请在确认 App 测试无误后关闭此issue.**
