### ISSUE TITLE
dmg 图标漂移

### ISSUE THREAD

**Issue by xkh01** [lihaoyun6/AppDimmer#9]
<img width="506" alt="image" src="https://user-images.githubusercontent.com/66284192/177256695-330898ef-5cb3-42c1-9375-3f69a292eb78.png">

环境 M1 MacBook Air, macOS 12.1

**Comment by lihaoyun6** [comment]
因为你的Finder现在处于显示隐藏文件的状态, 所以图标错误了. 关闭显示隐藏文件然后重新打开DMG就好了. 绝大部分人不会遇到这种问题, 这也不属于软件bug
